Melhorias - adequação ao novo padrão
betrybe/sd-0x-mysql-all-for-one pull request #15
Opened 2021-01-05 12:10 UTC by LizzardMedeiros

Fiquei com dúvidas sobre como colocar os requisitos no padrão, a melhor forma que achei foi deixando como itens comuns, como subtítulos ficou estranho.

2021-01-06 11:36 UTC, nato-re approved these changes

2021-01-09 01:13 UTC, StoneHg requested changes

2021-01-09 01:13 UTC, StoneHg commented on README.md
> +## Depois de terminar o desenvolvimento (OPCIONAL)
@albertosca precisa do opcional? se sim, seria uma boa a gente colocar no slide de modelo.

2021-01-09 01:13 UTC, StoneHg commented on README.md
> +- [Boas vindas ao repositório do projeto All For One!](#boas-vindas-ao-repositório-do-projeto-all-for-one)
acho que aqui também não precisa o boas vindas, já que tá antes do sumário @albertosca o que acha?

2021-01-29 19:23 UTC, albertosca reviewed
Pessoal, tenho zero contexto sobre o inicinho de Back-End, então deixarei essa CR nas hábeis mãos do @roziscoding e do @renatosousafilho! Ah, e falta numerar os requisitos no README, avaliador e testes!

2021-01-29 19:23 UTC, albertosca commented on README.md
> +## Depois de terminar o desenvolvimento (OPCIONAL)
É bom ter! Já houve confusão de estudantes que não fizeram esse passo e tiveram medo de perder a nota.

... Que slide de modelo? 😬

2021-02-02 15:22 UTC, roziscoding approved these changes

2021-03-04 18:49 UTC, roziscoding approved these changes

2021-03-04 19:24 UTC, brunobatista25 requested changes

2021-03-07 19:29 UTC, brunobatista25 approved these changes

2021-03-08 11:24 UTC, merged